extends:
  - https://github.com/reviewpad/.github/blob/main/reviewpad-models/common.yml

groups:
  - name: maitainers
    spec: '["fmallet", "ferreiratiago", "shay2025", "marcelosousa", "zolamk", "reviewpad-bot"]'

rules:
  # This rule is used to block pull request from being merged.
  # It is used on extended reviewpad common.yml configuration.
  - name: should block pull request
    description: Pull request should be blocked
    spec: $isElementOf("do-not-merge", $labels()) || !$isElementOf($author(), $group("maitainers"))

  - name: has reviewers
    description: Pull request has reviewers
    spec: $length($append($reviewers(), $requestedReviewers())) > 0

workflows:
  - name: changes to use cases
    run:
      - if: $hasFilePattern("docs/use-cases/**")
        then:
          - $info("Adding a new use case? Please update the [sidebars.js](/reviewpad/docs/blob/main/sidebars.js)")
          - $info("Adding a new use case? Please run the `checker`. You can find more information about the `checker` in [RELEASE.md](/reviewpad/docs/blob/main/RELEASE.md#test-the-reviewpad-configurations)")

  - name: changes built ins
    run:
        - if: $hasFilePattern("docs/guides/built-ins/actions/**") || $hasFilePattern("docs/guides/built-ins/functions/**")
          then:
            - $info("Adding a new built-in? Please update the [built-ins.mdx](/reviewpad/docs/blob/main/docs/guides/built-ins/built-ins.mdx)")
            - $info("Adding a new built-in? Please add a `caution` section if the built-in is not supported for both pull request and issue")
            - $info("Adding a new built-in? Please run the `checker` on the built-in reviewpad examples. You can find more information about the `checker` in [RELEASE.md](/reviewpad/docs/blob/main/RELEASE.md#test-the-reviewpad-configurations)")

  - name: assign reviewer
    run:
      - if: $assignees() != [] && !$rule("has reviewers") && $rule("review-strategy:ask")
        then:
          - if: $hasFilePattern("docs/**")
            then: $assignReviewers(["fmallet"])
          - if: $hasFilePattern("src/**")
            then: $assignCodeAuthorReviewers(1, $group("reviewers to ignore"), 3)

pipelines:
  - name: assign assignee
    trigger: $assignees() == []
    stages:
      - actions:
          - $info("The pull request is still in draft. Reviewpad will only assign a reviewer when the pull request is ready to be reviewed.")
        until: '!$isDraft()'
      - actions:
          - $review("REQUEST_CHANGES", "The pull request has git conflicts. Please fix them.")
        until: '!$hasGitConflicts()'
      - actions:
          - $assignAssignees([$author()])
