name: Create pull request to update latest version

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Create pull request to update latest version
    runs-on: ubuntu-latest

    env:
      LATEST_VERSION: v4

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build

      - name: Remove latest version
        run: |
          rm -rf versioned_docs/version-${{ env.LATEST_VERSION }}
          rm versioned_sidebars/version-${{ env.LATEST_VERSION }}-sidebars.json
          cat versions.old.json > versions.json

      - name: Add latest version
        run: yarn run docusaurus docs:version ${{ env.LATEST_VERSION }}

      - name: Build website with latest version
        run: yarn build

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.REVIEWPAD_TOKEN }}
          commit-message: "feat(release): update version ${{ env.LATEST_VERSION }}"
          branch: release/${{ github.ref_name }}
          delete-branch: true
          base: main
          title: "feat(release): Update version ${{ env.LATEST_VERSION }}"
          body: |
            ## Description
            This pull request updates the version ${{ env.LATEST_VERSION }} of the documentation.


            ## Code review and merge strategy (ship/show/ask)
            **Ship**: this pull request can be automatically merged and does not require code review
          labels: release
