# This workflows is based on Docusaurus documentation.
# For more details follow https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions
name: Deploy latest version

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Update latest version
    runs-on: ubuntu-latest

    env:
      LATEST_VERSION: v4

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build

      - name: Update latest version
        run:
          rm -rf versioned_docs/version-${{ env.LATEST_VERSION }}
          rm versioned_sidebars/version-${{ env.LATEST_VERSION }}-sidebars.json
          rm versions.json
          cp versions.old.json versions.json
          yarn run docusaurus docs:version ${{ env.LATEST_VERSION }}

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: update version ${{ env.LATEST_VERSION }}"
          git push origin main
